openapi: 3.0.0
info:
  title: Foo API
  version: 0.0.1

paths:
  /foo:
    get:
      operationId: getFoo
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: './definitions.yml#/components/schemas/GetFooResponse'
